spring:
  application:
    name: greeting-service
  cloud:
    config:
      uri: http://localhost:8888
  profiles:
    active: local
management:
  endpoints:
    web:
      exposure:
        include: refresh