management:
  endpoints:
    enabled-by-default: true
  info:
    enabled: true
server:
  port: 8080

feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
integration:
  concat:
    url: http://localhost:8081/concat
  hello:
    url: http://localhost:8082/hello